eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-main-client

app:
  client-url: http://service-client
  client1-url: http://service-client1
